replicaCount: 1

image:
  repository: vote
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 8080
  type: ClusterIP

env:
  LOG_LEVEL: development
  REDIS_HOST: redis-vote-master

ingress:
  enabled: true
  annotations:
    dev.okteto.com/generate-host: "true"
  hosts:
    - paths:
      - path: /
        pathType: Prefix

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
